version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - ROUTE_PREFIX=app
    networks:
      - my-network
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=salesTest
    networks:
      - my-network
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  my-network:
